export const fallbackLibrary = {
  version: 1,
  updatedAt: "2026-08-30",
  platforms: [
    { id: "audible", label: "Audible", color: "#f59e0b" },
    { id: "kindle", label: "Kindle", color: "#38bdf8" },
    { id: "goodreads", label: "Goodreads", color: "#a78bfa" },
    { id: "hardcover", label: "Hardcover", color: "#34d399" },
    { id: "paperback", label: "Paperback", color: "#fb7185" },
  ],
  series: [
    {
      id: "he-who-fights-with-monsters",
      title: "He Who Fights with Monsters",
      author: "Shirtaloon",
      accent: "#f59e0b",
      summary: "LitRPG progression fantasy with long-run momentum and a big backlog surface.",
      books: [
        { order: 1, title: "He Who Fights with Monsters", status: "read", platforms: ["audible", "kindle"], coverUrl: "https://covers.openlibrary.org/b/id/15229454-L.jpg" },
        { order: 2, title: "He Who Fights with Monsters 2", status: "read", platforms: ["audible"], coverUrl: "https://covers.openlibrary.org/b/id/14817883-L.jpg" },
        { order: 3, title: "He Who Fights with Monsters 3", status: "read", platforms: ["audible"], coverUrl: "https://covers.openlibrary.org/b/id/14816527-L.jpg" },
        { order: 4, title: "He Who Fights with Monsters 4", status: "read", platforms: ["audible"], coverUrl: "https://covers.openlibrary.org/b/id/12819130-L.jpg" },
        { order: 5, title: "He Who Fights with Monsters 5", status: "read", platforms: ["audible"], coverUrl: "https://covers.openlibrary.org/b/id/12819133-L.jpg" },
        { order: 6, title: "He Who Fights with Monsters 6", status: "reading", platforms: ["audible"], coverUrl: "https://covers.openlibrary.org/b/id/12819135-L.jpg" },
        { order: 7, title: "He Who Fights with Monsters 7", status: "queued", platforms: ["audible"], coverUrl: "https://covers.openlibrary.org/b/id/14817887-L.jpg" },
        { order: 8, title: "He Who Fights with Monsters 8", status: "queued", platforms: ["goodreads"], coverUrl: "https://covers.openlibrary.org/b/id/14817891-L.jpg" },
        { order: 9, title: "He Who Fights with Monsters 9", status: "queued", platforms: ["goodreads"], coverUrl: "https://covers.openlibrary.org/b/id/14817888-L.jpg" },
        { order: 10, title: "He Who Fights with Monsters 10", status: "unowned", platforms: [], coverUrl: "https://covers.openlibrary.org/b/id/14605657-L.jpg" },
        { order: 11, title: "He Who Fights with Monsters 11", status: "unowned", platforms: [], coverUrl: "https://covers.openlibrary.org/b/id/14817893-L.jpg" },
        { order: 12, title: "He Who Fights with Monsters 12", status: "unowned", platforms: [], coverUrl: "https://covers.openlibrary.org/b/id/15238884-L.jpg" },
      ],
    },
    {
      id: "the-land",
      title: "The Land",
      author: "Aleron Kong",
      accent: "#34d399",
      summary: "Chaos Seeds tracker for separating completed listens from the unread tail.",
      books: [
        { order: 1, title: "Founding", status: "read", platforms: ["audible", "kindle"], coverUrl: "https://covers.openlibrary.org/b/id/8568087-L.jpg" },
        { order: 2, title: "Forging", status: "read", platforms: ["audible"], coverUrl: "https://covers.openlibrary.org/b/id/13122555-L.jpg" },
        { order: 3, title: "Alliances", status: "read", platforms: ["audible"], coverUrl: "https://covers.openlibrary.org/b/id/11193343-L.jpg" },
        { order: 4, title: "Catacombs", status: "queued", platforms: ["audible"], coverUrl: "https://covers.openlibrary.org/b/id/12372305-L.jpg" },
        { order: 5, title: "Swarm", status: "queued", platforms: ["goodreads"], coverUrl: "https://covers.openlibrary.org/b/id/12373608-L.jpg" },
        { order: 6, title: "Raiders", status: "unowned", platforms: [], coverUrl: "https://covers.openlibrary.org/b/id/12504452-L.jpg" },
        { order: 7, title: "Predators", status: "unowned", platforms: [], coverUrl: "https://covers.openlibrary.org/b/id/8737387-L.jpg" },
        { order: 8, title: "Monsters", status: "unowned", platforms: [], coverUrl: "https://covers.openlibrary.org/b/id/10848258-L.jpg" },
      ],
    },
    {
      id: "arcane-ascension",
      title: "Arcane Ascension",
      author: "Andrew Rowe",
      accent: "#a78bfa",
      summary: "Sufficiently Advanced Magic sequence with progress, owned formats, and next reads visible.",
      books: [
        { order: 1, title: "Sufficiently Advanced Magic", status: "read", platforms: ["audible", "kindle"], coverUrl: "https://covers.openlibrary.org/b/id/10113994-L.jpg" },
        { order: 2, title: "On the Shoulders of Titans", status: "read", platforms: ["audible"], coverUrl: "https://covers.openlibrary.org/b/id/10261259-L.jpg" },
        { order: 3, title: "The Torch That Ignites the Stars", status: "queued", platforms: ["audible"], coverUrl: "https://covers.openlibrary.org/b/id/11378892-L.jpg" },
        { order: 4, title: "The Silence of Unworthy Gods", status: "unowned", platforms: ["goodreads"], coverUrl: "https://covers.openlibrary.org/b/id/12983788-L.jpg" },
        { order: 5, title: "When Wizards Follow Fools", status: "unowned", platforms: [], coverUrl: "https://covers.openlibrary.org/b/id/14821753-L.jpg" },
      ],
    },
  ],
};

